### ISSUE TITLE
view not found!

### ISSUE THREAD

**Issue by ronaldrios** [awssat/laravel-blade-audit#1]
D:\www\libros>php artisan blade:audit
view [D:\www\libros\resources\views\alerts\errors] not found!
view [D:\www\libros\resources\views\alerts\messages] not found!
view [D:\www\libros\resources\views\alerts\search] not found!
view [D:\www\libros\resources\views\auth\login] not found!
view [D:\www\libros\resources\views\auth\passwords\email] not found!
view [D:\www\libros\resources\views\auth\passwords\reset] not found!
view [D:\www\libros\resources\views\auth\register] not found!
view [D:\www\libros\resources\views\auth\verify] not found!

...

view [D:\www\libros\resources\views\vendor\pagination\simple-bootstrap-4] not found!
view [D:\www\libros\resources\views\vendor\pagination\simple-default] not found!
view [D:\www\libros\resources\views\welcome] not found!

   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to a member function map() on null

  at D:\www\libros\vendor\awssat\laravel-blade-audit\src\Commands\BladeAudit.php:169
    165|                     [new TableCell('All Views Information', ['colspan' => 2])],
    166|             ])
    167|             ->setRows(
    168|                 $result['info']
  > 169|                         ->map(function ($v, $k) {
    170|                             return [$k, $v];
    171|                         })
    172|                         ->filter(function ($v, $k) {
    173|                             return $k != 'Longest Line (chars)';

  Exception trace:

  1   Awssat\BladeAudit\Commands\BladeAudit::outputAllViews()
      D:\www\libros\vendor\awssat\laravel-blade-audit\src\Commands\BladeAudit.php:67

  2   Awssat\BladeAudit\Commands\BladeAudit::handle()
      D:\www\libros\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php:32

  Please use the argument -v to see more details.

**Comment by abdumu** [comment]
It's a windows os related issue. I tried to fix it in the latest release. 

Try it and reply if it's fixed.

**Comment by Braunson** [comment]
I'm getting a similar issue also, I'm running on Homestead and running the composer command inside Homestead but I still get that a few views are missing but they aren't?

**Comment by abdumu** [comment]
@Braunson latest version 1.7?

**Comment by Braunson** [comment]
@abdumu Yes just installed it.

**Comment by abdumu** [comment]
@Braunson 1.7 and getting the not found error on only few views ? no error message like the original issue?

**Comment by Braunson** [comment]
@abdumu Yes with no errors it it lists like 5 "missing views" which are not missing.

**Comment by abdumu** [comment]
@Braunson is there something different about these views? Compared to the "found" ones. 

Thanks for reporting

**Comment by Braunson** [comment]
@abdumu Nope just randomly views in the same folder `resources/views/vendor` but only some from that folder, I have a bunch of others as well as nested ones in there, they were found no problem.
